version: "3.7"

services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - artemis_network
    restart: always
    volumes:
      - type: volume
        source: pgdata
        target: "/var/lib/postgresql/data"

  server:
    build: .
    command: bin/docker/entrypoint
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    networks:
      - artemis_network
    ports:
      - 4077:4077
      - 4078:4078
    volumes:
      - type: bind
        source: .
        target: "/app"

networks:
  artemis_network:
    driver: bridge

volumes:
  pgdata:
