version: "3.7"

services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - artemis_network
    restart: always
    volumes:
      - type: volume
        source: pgdata
        target: "/var/lib/postgresql/data"

  server:
    build: .
    command: bin/docker/entrypoint
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - artemis_network
    ports:
      - ${ARTEMIS_API_PORT}:${ARTEMIS_API_PORT}
      - ${ARTEMIS_WEB_PORT}:${ARTEMIS_WEB_PORT}
    volumes:
      - type: bind
        source: .
        target: "/app"

networks:
  artemis_network:
    driver: bridge

volumes:
  pgdata:
