version: "3.7"

services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - atlas_network
    restart: always
    volumes:
      - type: volume
        source: pgdata
        target: "/var/lib/postgresql/data"

  server:
    build: .
    command: bin/docker-run
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    links:
      - db
    networks:
      - atlas_network
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: .
        target: "/app"

networks:
  atlas_network:
    driver: bridge

volumes:
  pgdata:
